### ISSUE TITLE
add support for installing libs alonside binaries

### ISSUE THREAD

**Issue by Blahah** [Blahah/bindeps#6]
User would specify both/either of `binaries` and `libraries`. Bindeps first looks for the files in the root of the unpacked directory, then if not found, looks in `bin` or `lib` subdirectories. Lib files get moved to a lib directory placed at `../lib` relative to the ruby gem bin directory.
 
yaml format would be like: 

```yaml
flux-simulator:
  binaries:
    - flux-simulator
  libraries:
    - barna.commons-1.22.jar
    - dom4j-1.6.1.jar
    - jdbm-2.3.jar
    - slf4j-nop-1.6.1.jar
    - barna.io-1.22.jar
    - groovy-all-1.8.4.jar
    - jfreechart-1.0.0.jar
    - xml-apis-1.0.b2.jar
    - barna.model-1.22.jar
    - guava-r08.jar
    - jsap-2.1.jar
    - xpp3_min-1.1.3.4.O.jar
    - barna.simulator-1.2.1.jar
    - itext-2.0.7.jar
    - reflections-0.9.5.jar
    - xstream-1.2.2.jar
    - commons-cli-1.2.jar
    - javassist-3.12.1.GA.jar
    - samtools-1.79.jar
    - commons-math-2.2.jar
    - jcommon-1.0.0.jar
    - slf4j-api-1.6.1.jar
  version:
    number: '1.2.1'
    command: 'flux-simulator'
  url:
    64bit:
      macosx: http://artifactory.sammeth.net/artifactory/barna/barna/barna.simulator/1.2.1/flux-simulator-1.2.1.tgz
      linux: http://artifactory.sammeth.net/artifactory/barna/barna/barna.simulator/1.2.1/flux-simulator-1.2.1.tgz
```
